### ISSUE TITLE
Add Phone Settings and Bluetooth

### ISSUE THREAD

**Issue by dmvvilela** [spencerccf/app_settings#14]
Can you implement the option to go to iPhone Settings (even if the app have its own) and to go to Bluetooth settings (even if it just android)?

**Comment by spencerccf** [comment]
Hi @dmvvilela, I will add these items to my queue.  I have a couple other items I need to finish up first but will get to these items next.

**Comment by dmvvilela** [comment]
Awesome!

**Comment by spencerccf** [comment]
@dmvvilela As of iOS 10.0 and above the direct access to Bluetooth Settings and others via: URL(string: "App-Prefs:root=Bluetooth") is no longer supported/approved by Apple.  Using this type of URL may get your app rejected from the app store.  The recommended URL to use is: URL(string: UIApplicationOpenSettingsURLString) which is currently what the plugin uses.  This is possible on Android so I will implement a new OpenBluetooth function for both iOS and Android platforms.  Unfortunately, the iOS function will behave the same as the open setting function does due to the restriction of using: URL(string: UIApplicationOpenSettingsURLString)

**Comment by spencerccf** [comment]
@dmvvilela I can get this added into plugin for Android side.  iOS will behave as it does today.

**Comment by spencerccf** [comment]
@dmvvilela This has been added to the Android side of the plugin.  iOS will still open App Settings.

**Comment by spencerccf** [comment]
@dmvvilela This has been added to the Android side of the plugin. iOS will still open App Settings.  I'm going to close out this issue.  Please let me know if you have any questions or need additional feature updates.
