### ISSUE TITLE
Notification settings on iOS opens just settings of the app

### ISSUE THREAD

**Issue by Renesanse** [spencerccf/app_settings#144]
last version from pub.dev

**Comment by plinkos** [comment]
This is correct behavior on iOS.  Apple does not allow access to specific screens like Android does. In order to do similar on iOS you need to implement notifications in your code and at least prompt the user once for notification permission.  Then that permission will end up in the App Settings which is where this plugin will take the user on subsequent requests.

**Comment by Renesanse** [comment]
@plinkos ok, thx for answer
