### ISSUE TITLE
app crushed after changing notification status and coming back to app

### ISSUE THREAD

**Issue by Alice-in-korea** [spencerccf/app_settings#168]
**AppSettings.openNotificationSettings()**

After changing notification status and coming back to app, my app crushed.

It does not happen with Galaxy Note 10+(Android12), Galaxy Z flip3(Android12), but it does with new Galaxy phons such as Galaxy S21(Android13), S22(Android13).

**Comment by vasa137** [comment]
Same issue, when notifications are turned off, app crashes in the background. Android 13

**Comment by lead-SAP** [comment]
Same here..this also happens with the package 'permission_handler'.

**Comment by lead-SAP** [comment]
As far as I understand, this issue is similar to https://github.com/spencerccf/app_settings/issues/163

**Comment by sevbauer** [comment]
Same here

**Comment by afn1988** [comment]
Same, 
any news on this?

**Comment by sevbauer** [comment]
As far as I know, this issue is not related to the plugin.

It is the intended behavior of Android OS to restart the app when permissions change from "allowed" to "denied."

Now, when you run the app with the debugger, Android restarts the app, but the debugger loses its connection and displays a white screen. If you try this in Release Mode (without the debugger), the app simply starts over from the beginning, with the permissions denied.

I believe there is no way to avoid restarting the app. If you want to create the illusion that the app has not restarted at all, you must manually save and restore the app state on your own, similar to what WhatsApp and Spotify do.

**Comment by AbdallahLabib** [comment]
I have the same issue ..  I tried app_settings 5.1.1 and app_settings 4.1.8 on Android 34 and I got the same result!
