### ISSUE TITLE
Crash on ios 14 and 12 , app_settings: 4.3.0

### ISSUE THREAD

**Issue by 015-Michelle** [spencerccf/app_settings#191]
Hi I found a problem with the plugin starting from version 3.2.0 , which causes a crash, mainly because of the addition of "import StoreKit".

details:
dyld: Symbol not found: _$s8StoreKit03AppA0O23showManageSubscriptions2inySo13UIWindowSceneC_tYaKFZTu
  Referenced from: /var/containers/Bundle/Application/C83FD4CF-1E07-4FE2-837B-FB99859317CF/Runner.app/Runner
  Expected in: /System/Library/Frameworks/StoreKit.framework/StoreKit
 in /var/containers/Bundle/Application/C83FD4CF-1E07-4FE2-837B-FB99859317CF/Runner.app/Runner
(lldb)

**Comment by navaronbracke** [comment]
The function `showManageSubscriptions` is only used from iOS 15 onwards. 

See https://github.com/spencerccf/app_settings/blob/master/ios/Classes/AppSettingsPlugin.swift#L70-L73 and https://github.com/spencerccf/app_settings/blob/master/ios/Classes/AppSettingsPlugin.swift#L38-L43

What XCode version and iOS version is this happening on?

**Comment by 015-Michelle** [comment]
My xCode version is 14.3, and the iOS version will crash if it is lower than 15 (12 or 14), 15 and 16 are normal.

**Comment by 015-Michelle** [comment]
My xCode version is 14.3, and the iOS version will crash if it is lower than 15 (12 or 14), 15 and 16 are normal.

**Comment by navaronbracke** [comment]
I'll take a look on iOS 12, 13 and 14. Maybe the availability check isn't working as expected?

**Comment by navaronbracke** [comment]
@015-Michelle I ran the example app on an iOS 14.0 Simulator and it runs fine for me.
The deployment target of the app_settings example app is `iOS 11.0`.

I did have to use this dependency override in my `pubspec.yaml`

```
  app_settings:
    git:
      url: git@github.com:navaronbracke/app_settings.git
      ref: fix_v5_ios_compile
```

due to a build error during the Cocoapods install step `NoMethodError - undefined method `source_tree'`.

I fixed that in my `fix_v5_ios_compile` branch (had to regenerate some metadata for the plugin, probably something was outdated?), hence the git dependency override. There is a PR open to fix that upstream in `app_settings` but @spencerccf still has to review that one.

Can you verify using the dependency override? See https://dart.dev/tools/pub/dependencies#git-packages

**Comment by 015-Michelle** [comment]
@navaronbracke  Thanks！I updated the app_settings to 5.0.0, and iOS12 can run normally. This version that works normally still imports StoreKit. I mistakenly thought it was the reason for importing StoreKit.
